### ISSUE TITLE
I am getting the below exception when I am trying to run the jar file.

### ISSUE THREAD

**Issue by ArchanaSomasekhar** [GruppoFilippetti/vertx-mqtt-broker#9]
For running I am using the command below:
java -jar target\vertx-mqtt-broker-2.3.0-SNAPSHOT-fat.jar -c config.json

/C:/Users/archana_somasekhar/git/vertx-mqtt-broker/target/vertx-mqtt-broker-
2.3.0-SNAPSHOT-fat.jar!/
2016-07-27 17:38:03 INFO   io.github.giovibal.mqtt.security.impl.OAuth2Authentic
atorVerticle Startd MQTT Authorization, address: mqtt.authenticator.oauth2
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 1883] [security]  [socket_idle_timeout:120]
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 11883] [websocket,security]  [socket_idle_timeout:120]
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 1884] [security,retain_disabled]  [socket_idle_timeout:120]
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 11884] [websocket,security,retain_disabled]  [socket_idle_timeout:120]
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 1885] [retain_disabled]  [socket_idle_timeout:120]
2016-07-27 17:38:04 INFO   io.github.giovibal.mqtt.MQTTBroker Startd Broker ==>
[port: 11885] [websocket,retain_disabled]  [socket_idle_timeout:120]
io.vertx.core.VertxException: io.vertx.core.file.FileSystemException: java.nio.f
ile.NoSuchFileException: C:\certs\tenant1\tenant1.key
        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:303)
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:458)
        at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:472)
        at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:160)
        at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:135)
        at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:129)
        at io.github.giovibal.mqtt.bridge.EventBusBridgeServerVerticle.start(Eve
ntBusBridgeServerVerticle.java:80)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentMana
ger.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359
)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileExcep
tion: C:\certs\tenant1\tenant1.key
        at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java
:710)
        at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java
:702)
        at io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImp
l.java:285)
        at io.vertx.core.net.impl.KeyStoreHelper.lambda$create$2(KeyStoreHelper.
java:82)
        at io.vertx.core.net.impl.KeyStoreHelper$KeyCert.loadPrivateKey(KeyStore
Helper.java:212)
        at io.vertx.core.net.impl.KeyStoreHelper$KeyCert.loadStore(KeyStoreHelpe
r.java:202)
        at io.vertx.core.net.impl.KeyStoreHelper.getKeyMgrFactory(KeyStoreHelper
.java:130)
        at io.vertx.core.net.KeyCertOptions.getKeyManagerFactory(KeyCertOptions.
java:43)
        at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:308)

        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:239)
        ... 13 more
Caused by: java.nio.file.NoSuchFileException: C:\certs\tenant1\tenant1.key
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.j
ava:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.jav
a:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.jav
a:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystem
Provider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at io.vertx.core.file.impl.FileSystemImpl$12.perform(FileSystemImpl.java
:706)
        ... 22 more

**Comment by giovibal** [comment]
It depends on tls configuration.
To quick start the broker, without all optional configurations, you can put this in "config.json"

`
{
  "brokers": [
    {
      "tcp_port": 1883,
      "socket_idle_timeout": 120
    }
  ]
}
`
